### ISSUE TITLE
devv-specific feature proposal :: another unit testing folder / environment

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#496]
I'm very happy about the new e2e testing thing I'm working on, of course also realising this should be in concert with a lot of unit testing.  Would it be okay if I opened a new folder from root (maybe called something like "/cafe") for unit testing ?  I'll be using Mocha and the source (if okay) will be in CoffeeScript.

**Comment by thepian** [comment]
I think there are two thoughts when it comes to testing code structure. One is to keep it with the source, another is to keep it separate. I find that keeping it separate often comes from Mavens structure of /main and /test.

For unit tests I prefer to use the file extension to match the tests I.E. '*.spec.js'. If there are few test specs they can be saved along with the source they test. If there are many they can be put in a sub-package.

Two benefits of keeping source and unit tests in the same folder are that you can switch between them without IDE support, and that since they are visually close you are nudged towards writing more tests.

For integration, e2e etc the tests are often cross-cutting, so they don't fit very well with the source structure. For those I think they are best placed in a root /test directory.

Now on to your question, which I've probably misunderstood:

I don't see any problem with mixing JS and CoffeeScript files in the same source tree, so I would suggest that you put your new test scripts under /test/unit in the appropriate area. That is where the existing tests are (even if I would put them with the source)

Or are you talking about unit testing of the new examples? In that case I would put it under /test/examples/unit or /examples/test/unit

**Comment by kulicuu** [comment]
This would be unit testing of Ss stuff.  The example apps should have their own unit tests kept in their own repositories; on the other hand and at the same time there would be Ss specific e2e tests related to specific apps and even specific configuration states of those apps which be in the e2e folder -- though I haven't figured out how best to organise that.  There's an "/appLibrary" folder already, something like that but for specific e2e testing scripts.  Ultimately, these would be documented in the readme and eventually maybe invocable by npm script or gulp script from project root.  Perhaps some canonical e2e acceptance routine before a big PR.

**Comment by kulicuu** [comment]
I like the idea of having tests close to source-- in my own work the two are in the same file indeed I write the implementation to be self testing and report its status through the console.  That's for prototyping though, and long term goal is for full unit testing coverage across all relevant levels of abstraction.  Maybe in practice not so feasible, but a little pays off a lot in this area.  
Again I think it's an interesting idea to have the tests close to the source, and I think it makes intuitive sense; however, in this context I think probably not suitable. Why I think this: It's ideosyncratic the way people test; I have some strategy I like and some particular set of libraries and styles I'll use for it.  So it would make sense to allow this to be loosely coupled, to allow some space for multiple non-exclusive developmental approaches to coverage to emerge... et cetera.

**Comment by thepian** [comment]
I think we have to have a single test suite in SS. Allowing each contributor to make a whole new setup will become a mess. When you have two it is slightly confusing, when you have 5 it is a mess.

I think there can still be some variation in how tests are written, but there has to be a minimum level of consistency.

If the SS source wasn't consistent and minimal I would have dropped it the first day I looked at it. I would expect many others would too. While it can be frustrating to write code in "other peoples crappy way", I don't see a way to avoid it.

The only exception would be if there is a large body of work that we are importing and we don't have the resources to refactor it. Then it has to be grafted on, at least initially.

**Comment by kulicuu** [comment]
Reasonable position.  I don't agree, but it's reasonable.  One compromise would be to put the whole melange into one major test folder.  If that's not okay then I'm happy to test according to local convention. I'll revisit this point another time.

**Comment by thepian** [comment]
I think this is really up to Paul to make a call on. I'm just stating my opinion.

**Comment by paulbjensen** [comment]
In my experience with git submodules (a commercial project with Vodafone), they're a world of pain, because they complicate how you manage the code. You have to synchronise multiple git repos, and ensure that changes in git submodule folders do not end up getting tracked and pulled in by the local main repo. I would recommend avoiding them.

In my experience with e2e testing, I've resorted to using [Cucumber](http:/cukes.info) and a combination of selenium-launcher and soda to test web apps end to end. As for a web framework, the framework was never originally tested, and so the question of how to do e2e testing on it will need some thinking.

**Comment by kulicuu** [comment]
Wow.  I'll have to think about that some days before responding.  I'm really excited about submodules--admitedly I'm new to them, but quite taken with the possibilities.

**Comment by thepian** [comment]
I used to love them as well. I use them to make my own development simpler. However they do introduce dependency management in addition to the one with npm.

An alternative would be to have an example repository under socket stream say `/socketstream/examples` and npm publish that as "socketstream-examples". We could then put it as a devDependency for socketstream.

**Comment by kulicuu** [comment]
Yeah I'm not contemplating extreme measures or anything, whatever is generally accepted will be fine.  How I use them in my other work another issue.

**Comment by kulicuu** [comment]
I was definitely still thinking more about the way I'll be doing acceptance testing broadly speaking.  For today at least, the priority is emphasisng development on my fork, organising the branches there, making a partially autonomous staging environment there, which could differ somewhat from the upstream, even though designed inclusive with purpose to send stuff there.
