### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#505]
Thoughts?

**Comment by arxpoetica** [comment]
http://semver.org/ FYI

**Comment by kulicuu** [comment]
Yes.

**Comment by thepian** [comment]
Yes

**Comment by paulbjensen** [comment]
Cool - please go ahead.

**Comment by thepian** [comment]
Can we get an acceptance criteria for this, please? Not sure what need to be done other than documenting a bit under contributions

**Comment by paulbjensen** [comment]
At the start of the project and to this day SocketStream followed a pattern of 0.<x> being major updates (i.e. Owen rewriting it and making big changes), which goes against the convention of <x>.0 being major updates.

If we want to switch to <x>.0, then we need to look at what would be a major update to SocketStream, as well as when we'd want to classify SocketStream as stable. During the time I've been looking after the project, I chose to focus on making the 0.3 branch stable rather than rewrite the framework as Owen planned to with SocketStream-0.4.

I think that with some of the new features that have been added, 0.4 should be the next stage of minor updates, and 1.0 should be when the project is considered stable.

Stable in my opinion would be the following:

- Good code coverage
- Good documentation
- 0 bug issues on GH (just feature requests and queries)

Tutorials and example apps would be nice, but are not a deal-breaker.

We would also need to communicate this change to the community, as they've been used to the existing pattern of updates.

On a side note, I just want to express my thanks to all of you for your recent work with SocketStream, I appreciate it.

**Comment by arxpoetica** [comment]
So just really quick, I think we can press forward, like Paul is saying to reach `0.4`. BUT.

The value of semver is that it gives an outward community something really predictable and reliable to look to.

 * Users will know that any `0.0.x` release is just bug fixes (non-breaking),
 * Users will know that any `0.x.x` release may include both bug fixes and or improvements or changes to the platform (that are non-breaking and 100% backwards compatible), and,
 * Users will know that any `x.x.x` release will include backwards incompatible changes *or/and* be a major milestone change with big enough feature changes to warrant a major release upgrade.

(This site says it a little better: http://semver.org/)

But I think, since we've been talking about `0.4` forever, it makes sense to continue on that path, and _after_ that release start using semver from there on out. (so, `0.4.x` for bug fixes, `0.5.x` for larger features and improvements, and `1.x.x` for breaking changes, for example).

Not to beat a dead horse, but I think there's massive value in using something people are familiar with.

**Comment by thepian** [comment]
I see 0.4 as non-breaking, at least for 99% of users. There are new APIs, but old ones are supported.

Does this involve any code change? semver module for instance

**Comment by arxpoetica** [comment]
@thepian interesting. If it's truly non breaking then 0.4 would sort of fall in step, with semver. Even so, I would keep it 0.4 for clarity.

As to a module, there might be one, but the change I'm proposing is only just something to agree on (or not).

**Comment by thepian** [comment]
+1

**Comment by arxpoetica** [comment]
Okay, cool. I'm gonna go ahead and call this sufficiently vetted, and close it. We can discuss further (if needed) once the `next`/`0.4` release lands.
