### ISSUE TITLE
Engine.io client as module and optional

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#533]
When we upgraded to the latest engine.io the client was left as a library. It should be a CommonJS module, so it can be excluded if you use SockJS. Additionally the client shouldn't be in the codebase, but rather be fetched from an npm module.

@kulicuu Could you add some details about this so we can get a solid improvement done.

**Comment by paulbjensen** [comment]
It's possible that this could be moved out, in fact SocketStream originally has socket.io as the bundled library, which could be swapped out with engine.io via ss-engine.io or sockjs with ss-sockjs.

ss-engine.io hasn't been updated in a while, but could be updated and thus the code for web sockets is loaded that way, rather than being inside the core of SocketStream.

**Comment by thepian** [comment]
I don't think it has to be a SocketStream plugin as such(although that is also an option). I merely think that the client code shouldn't be a mandatory library loaded regardless, but rather a system module that will be loaded if needed given the configuration.
