### ISSUE TITLE
0.4.2: Template engine is always default

### ISSUE THREAD

**Issue by hulmgulm** [socketstream/socketstream#540]
Hi,

I've defined my client to load the templates from the angular directory (tmpl: 'angular').
Then I've set the template engine like this:

ss.client.templateEngine.use('angular');

However I get my templates always formatted with the default formatter.

The same results for

ss.client.templateEngine.use('angular', '/templates/angular');
ss.client.templateEngine.use('angular', './templates/angular');
ss.client.templateEngine.use('angular', './angular');
ss.client.templateEngine.use('angular', '/angular');

If I set a breakpoint at lib/client/template_engine.js function selectEngine I can see that the code path is always "templates/angular" and the engines are ".", "./angular", "./templates/angular" and therefore never match.

Thank you,
   Andreas

**Comment by thepian** [comment]
The odd thing is that there is a test covering this, so there must be a discrepancy somewthere. Either,

1) I'm not testing fully enough
2) There is something else in your client defintion that differs

Could you supply a client definition that gets the wrong templates ?

**Comment by thepian** [comment]
does it work if you use `{tmpl: '/angular'}` ?

**Comment by thepian** [comment]
Will be fixed in 0.4.3 with other asset related issues

**Comment by paulbjensen** [comment]
When trying this branch with Dashku's integration tests, Dashku is able to boot up, but we've now noticed that the ss.tmpl objects all begin with 'templates-' at the front, was this a deliberate change?

**Comment by thepian** [comment]
no, I tried to make everything work as before. Are they still the same type?

**Comment by thepian** [comment]
To my knowledge there is 100% test coverage on template output, so I must be missing something.

Could you have a look at the tests to see if they are as expected?

**Comment by paulbjensen** [comment]
Yep, I'll take a look. I'll also provide a few more details relating to the behaviour I saw in Dashku.

**Comment by paulbjensen** [comment]
I think I know what is happening now, some explanation.

If you checkout a copy of Dashku from here: https://github.com/dashku/dashku, then after running <code>npm install</code>, you run <code>npm link</code> to get Dashku to load a local copy of the Socketstream repo rather than the version specified in package.json, like so:

```
npm link PATH_TO_SOCKETSTREAM_REPO
```

After doing that, once you've got mongodb and redis running, run <code>npm start</code>, and visit <a href="http://localhost:3000">localhost:3000</a>. You should see something like this:

![screen shot 2015-06-07 at 11 08 52](https://cloud.githubusercontent.com/assets/3840/8023478/a2cb4274-0d05-11e5-8254-bdb89d33a981.png)

If you open your inspector, on the console panel you'll see this:

![screen shot 2015-06-07 at 11 09 47](https://cloud.githubusercontent.com/assets/3840/8023481/c0a31b28-0d05-11e5-839a-e0e7b4685114.png)

If you run ss.tmpl in the inspector console panel, you should see this:

![screen shot 2015-06-07 at 11 11 12](https://cloud.githubusercontent.com/assets/3840/8023500/f63cf2a4-0d05-11e5-9969-1f03e454d1d3.png)

All of the Hogan.js templates in ss.tmpl begin with 'templates-' at the front of them. All of those Hogan.js template files live in the client/templates folder. I think that this might be linked.

**Comment by thepian** [comment]
But are they rendered with the hogan template engine or with the default one?

**Comment by thepian** [comment]
Ah. I know what it is ...

I changed the base path of everything to be `client` rather than the type specific directory so we can have more bundling freedom. The default ID is encoding the path not the file name, as it should.

I will make a special case for the templates directory.

**Comment by thepian** [comment]
Your issue is now fixed in the pack-assets-fix branch, misleading name, but it's the remaining work for 0.4.3

**Comment by paulbjensen** [comment]
Fantastic, thanks @thepian.

**Comment by thepian** [comment]
As a sidenote, if you had checked the unit tests it would be clear that the assertions are wrong as they include `templates-`.
