### ISSUE TITLE
Session sharing between Websockets and HTTP

### ISSUE THREAD

**Issue by hulmgulm** [socketstream/socketstream#543]
Hi,

we are sharing sessions between websocket and HTTP requests.

We see that in HTTP requests the connect.sid gets processed by cookie-parser and validated but during the websocket connection cookie-parser is not called.

The result is that the HTTP request sees a session ID like this:

UlTp92sLseIuSepPWpJr6RLPOip-SdBI

and the corresponding websocket session ID looks like this:

s%3AUlTp92sLseIuSepPWpJr6RLPOip-SdBI.z6gbo9fzFjCewBMPeoH4jen1ZgZOG7A0FQ2ZyVvsJgQ

This leads to problems as they are two separate sessions in the session store.

How can we solve this problem?

Thank you,
   Andreas

**Comment by hulmgulm** [comment]
Small update:

we use connect-route for routing our HTTP requests. I've appended a middleware before the connect-route middleware to add session information to the request object.

To get the correct session, I do the following:

var sessionId = encodeURIComponent('s:'+signature.sign(req.session.id,socketstream.session.options.secret));
socketstream.session.find(sessionId, null, function(session) {

Is this the intended way to do this?

**Comment by paulbjensen** [comment]
Hi @hulmgulm, thanks for the detailed bug info. What version of SS are you using?

SocketStream is meant to allow both HTTP and WS to access the same cookie, so this sounds like a bug, possibly linked to the engine.io upgrade but that is more of a hunch than anything. I will take a look when I get the chance; I'm finishing work at my client this week, so I will have plenty of time to sink my teeth into the project.

**Comment by kulicuu** [comment]
I'm looking into this now.  If anyone is available to chat on gitter about it I'm interested in getting more info about the issue.

**Comment by arxpoetica** [comment]
@kulicuu you might want to also see issue #539 which I opened. Different scenario, but same “shared session” problem. There's additional background cited in that ticket.

I'll be watching both of these tickets closely.

**Comment by kulicuu** [comment]
There are two closely related but distinct issues here.  

One has to do with SocketStream's built-in http sessions handling and the extent of its sharing with the ws.  

The other, as in the Koa thread above and my own reported issue [here at issue 475](https://github.com/socketstream/socketstream/issues/475), has to do with bringing in another library (Express/Connect) and merging its stack / sessions with SocketStreams.  

In the second case, the old hack was broken by the new strategies code.  I don't see that as necessarily a bad thing, if there is a better way we should be doing it; basically my position at the end of #475 .

In the first case, we should definitely have sessions shared in a way that is well-engineered, and will additioanally provide an easy way to accomplish the first issue.  Please have a look at the gitter thread for notes, and I'll be online to work/chat on this on Sunday during the day (UTC+2 ) to discuss and hopefully generate a good design solution.

**Comment by arxpoetica** [comment]
Okay. Not sure I know the distinction. As for well-engineered, I agree. I was thinking this morning that the `ss` api ought to expose the session in a meaningful way.

**Comment by kulicuu** [comment]
How would you like to see that API session exposure ? A sketch of the general idea ?

**Comment by arxpoetica** [comment]
Thanks for looking at things. I've been looking at those very files too, logging and digging, etc. I feel like I'm closer to getting the mechanics. Something that I never knew before—by default we're using express-session (part of the connect universe) to handle sessions. That's not necessarily a bad thing, but it's a pretty big "oh" and should be documented. Good news is, this situation has made me dig quite a bit to understand the guts of the machine (as you call it).

**Comment by kulicuu** [comment]
Yes, I'm learning about signed cookies.

@hulmgulm thanks for the code snippet above.  very good clues.

**Comment by kulicuu** [comment]
Okay I got it (I think so anyway). Had to set the sessionId to signed cookie value in engine.io thing.  Going to lunch now.  Will clean it up and maybe PR this afternoon.

**Comment by kulicuu** [comment]
I think this has good fix now with most recent merge, would like to hear results of verification.

**Comment by arxpoetica** [comment]
Can you describe the changes you made? I've had a look over. Seems like your passing options and adding a secret in various places. What additionally is going on?

**Comment by kulicuu** [comment]
Right cool, so the problem was something arcane to do with the way cookies are actually handled in this case.  They're signed for security by cookie-parser, but the session handling initialisation for the engine.io wasn't parsing them back to the id that would enable lookup of the session.  So, the initial solution (yesterday) simply used cookieParser's `signedCookie` function to parse that back in the `processSession` function in the engine.io transport, with the secret baked in.  Today I added the secret attribute to the session's options object (this can be edited from the main app file with like `ss.session.options.secret = "newSecret";`), and in the websockets loader function in socketstream.js I added `session.options` to the arguments, and additionally edited all the functions in the chain to the `processSession` function in engine.io transport index.js.  That's pretty much it.  I alias console.log with c to make it a bit faster to quickly log and unlog a lot of things.

**Comment by arxpoetica** [comment]
Let me see if I'm understanding correctly. In other words, alternatively, the following is now possible:

```
ss.session.options = {
	secret: 'some session secret',
	cookie: {
		[...settings...]
	},
	[...additional session settings...]
}
```

Is this correct? You've provided an API basically to alter the session store?

**Comment by kulicuu** [comment]
Nothing so interesting.  I established a default value for secret in the session options.  You can alter it before creating/starting the server.  Before when I'd upgraded the engine.io and connect, I'd neglected to handle the cookie the same on both parts.  So I'm just cleaning up a bug I introduced.

**Comment by arxpoetica** [comment]
I see, I see.

SO. I *think* the other issue I've opened is going to actually require a more robust session API. (I _think_.) I won't elaborate any further here, but I'll open that convo up elsewhere so we can bounce it back and forth.

In essence—it's possible (I might be wrong) that it's currently not possible to share sessions w/ some kinds of middleware in our current set up (for example, Koa). Like I said, I'll elaborate elsewhere, so I don't take this particular ticket too far tangent.

**Comment by arxpoetica** [comment]
I think this actually fixed my issue. It started working after I updated. See: https://github.com/socketstream/socketstream/issues/539#issuecomment-106666039

**Comment by thepian** [comment]
@kulicuu Hmm, does this mean that you need to configure the session secret twice in the app ?

And shouldn't the API be like for the client

`ss.session.set({ .. });`

**Comment by kulicuu** [comment]
I only had to set the secret once.  It's been a couple of weeks.  I'll have a look at it tomorrow.

I used `t.session.options.secret = "someNewSecret"`, like `ss.session.options.secret = "someNewSecret"` once in the main app file. 
https://github.com/socketstream/ss-examples/tree/master/react-and-coffeescript
 I think it goes to both, which is why the sessions are now shared between http and engine.  I tested very manually, with console.log and some diagnostic calls from my example app; the thing I should be obligated to is implementing some write-behind-testing unit testing for this. And then later really it's the e2e testing which was a long term goal.
