### ISSUE TITLE
Switch default app.js to use connect

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#568]
Our cannonical example is based on http. If you have any complexity in your app on the serverside that isn't a very good logical structure, you will need some middleware, and Socketstream should not be the one managing this.

We should deprecate append/prepend of middleware and leave it up to the web framework of choice.

Or perhaps Express should be our cannonical example, it's got a slight edge over Connect in downloads.

@paulbjensen Agree?

**Comment by thepian** [comment]
I think we want to move away from being a middleware framework as fast as possible. connect is 1000x more popular, it is the de-facto approach and it isn't anything we can do better.

By 0.5 I'd like to have cut out standard middlewares as dependencies.

**Comment by arxpoetica** [comment]
SocketStream uses Connect under the surface in various places. It might make sense to be more explicit about that relationship, but I'm also not sure I understand what your proposing.

**Comment by paulbjensen** [comment]
@arxpoetica @thepian SocketStream basically uses connect middleware, and provides append/prepend as ways to insert other connect-middleware before the initial stack. That is how Dashku is able to append a REST API to the dashboard single page app.

On the old version of the website, there was an example in the tour that featured a way to load SocketStream and Express together. I can try and dig it out and make it more obvious for users.

The HTTP layer in SocketStream does need a closer look. The time when I experimented with alternative approaches to HTTP in https://github.com/anephenix/vorka 2 years ago I found that it was better to use a pure HTTP server over Express (3), and Express 4 has removed all of the connect middleware to be faster. If you do some rough benchmarking requests using a tool like siege, you'll see that Vorka does better than Express, and way much better than Hapi.

**Comment by arxpoetica** [comment]
Interesting...

**Comment by thepian** [comment]
I'm proposing to reduce what SocketStream does to focus on the streaming. The prepend and append only affect middleware configuration which is something 99% of users will do with a mainstream framework. That whole router code is quite smelly and it seems we have a couple of issues in view matching as a results.

The benefit of mainstream frameworks is the vastly bigger volume of people knowing how to solve problem X. For general purpose REST endpoint hosting there are tons of use cases, most of which are not really related to streaming.

In most projects the main hurdle is getting to the first release. Reading Pauls resonse I hear, "SocketStream is a specialised framework squarely focused on top performance in all areas. It might limit your ability to do an MVP fast in order to push you towards performance".

I'm curious what the cost is of using Express middleware over SocketStream's approach for the regular endpoints.

**Comment by thepian** [comment]
Perhaps I should just provide an example and support for a way to run a SocketStream App without ss.http.middleware

**Comment by kulicuu** [comment]
Why not just make the core router use Connect ?

**Comment by thepian** [comment]
That was my thought of thinking. It seems the argument is performance of serving views which puzzles me a bit. I would expect the difference between the alternatives to be on the order of 1ms

**Comment by thepian** [comment]
I'm looking at the various parts of ss.http

I see require connect in there, but somehow it's not used for making the server. As a user of SS, I find that confusing.

**Comment by paulbjensen** [comment]
Hi,

The router code is smelly and does cause issues, especially when people want to return 404s for routes that are not matched, hence I think it needs a fresh look.

The reason why SocketStream was built on connect as opposed to Express was because it's focus at the time was on supporting Single Page Apps, and Express bundled a bunch of middleware by default that wasn't necessary to that goal.

The section I put about performance was more about being how bloated some web frameworks had become in 2013 - Express has recognised this and hence why the middleware stack is much thinner in v4 than in v3.

Henrik's point is a good one - what is SocketStream's purpose? It does a lot of things, but trying to maintain a framework doing all of those things is a big job, and usually libraries come out which do the job a lot better, so maybe now is the time to re-assess that. It won't be an easy thing to do, as it will require a lot of time and thought.

And that is the other thing - I hardly have the time to work on SocketStream, given the book for Manning publications and moving to another country. I think that if SocketStream is going to progress then it will need someone with more time than I have, therefore I'd like to find someone to take over leading the project.

**Comment by thepian** [comment]
I think I have found a better approach than my original suggestion, so I will close the issue
